apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jj5y
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-jj5y@sha256:d28db3f5521db16f3bce532f1aa7c3111a9a7a308a27e739a6efadffbe4918d4
        name: my-nodejs
        resources: {}
status: {}
